export type PostLang = { title: string; excerpt: string; content: string };
export type Post = { slug: string; date: string; lang: { [key: string]: PostLang } };

export const posts: Post[] = [
  {
    slug: "uae-biodiversity-credits-cop28",
    date: "2025-08-01",
    lang: {
      en: {
        title: "UAE Biodiversity Credits: Opportunities After COP28",
        excerpt: "COP28 in Dubai placed the UAE at the center of global climate finance. Here's how the country is leveraging its COP presidency to build a biodiversity credit market.",
        content: `<p>The UAE's hosting of COP28 in Dubai in 2023 was more than a diplomatic achievement — it positioned the country as a serious player in international climate finance. The UAE Presidency's focus on the Global Stocktake, loss and damage funding, and the UAE Consensus on tripling renewable energy capacity has been matched by domestic policy action, including the expansion of marine protected areas and mangrove restoration programs.</p>
<p>The Abu Dhabi Global Market (ADGM) has taken a leading role in developing the regulatory infrastructure for voluntary carbon and biodiversity credit markets. ADGM's Carbon Exchange, launched in 2023, provides a regulated platform for carbon credit trading in the region, with ambitions to become the Gulf's primary carbon trading hub.</p>
<p>UAE's biodiversity credit market is nascent but growing rapidly. The country's extensive mangrove restoration program — targeting 100 million mangroves by 2030 — is a key source of both carbon and biodiversity credits. Abu Dhabi's mangroves sequester 0.6-1.7 tonnes of carbon per hectare per year and provide habitat for rare marine species.</p>
<p>For international buyers seeking Middle Eastern carbon and biodiversity credits, the UAE offers regulatory stability, strong government backing, and alignment with international standards. Expect significant credit issuances from UAE mangrove and coral reef restoration projects over the next three to five years.</p>`,
      },
      ar: {
        title: "ائتمانات التنوع البيولوجي في الإمارات: الفرص بعد COP28",
        excerpt: "وضع COP28 في دبي الإمارات في مركز التمويل المناخي العالمي. إليك كيفية استفادة البلاد من رئاستها لـ COP لبناء سوق لائتمانات التنوع البيولوجي.",
        content: `<p>استضافة الإمارات لـ COP28 في دبي عام 2023 كانت أكثر من إنجاز دبلوماسي — فقد وضعت البلاد كلاعب جاد في تمويل المناخ الدولي. ركّز رئاسة الإمارات لـ COP28 على الجرد العالمي، وتمويل الخسائر والأضرار، والتوافق على مضاعفة طاقة الطاقة المتجددة ثلاث مرات.</p>
<p>تولّى مركز أبوظبي للأسواق المالية (ADGM) دوراً رائداً في تطوير البنية التحتية التنظيمية لأسواق الكربون الطوعية وائتمانات التنوع البيولوجي. يوفر بورصة الكربون التابعة لـ ADGM، التي أُطلقت عام 2023، منصة منظمة لتداول ائتمانات الكربون في المنطقة.</p>
<p>سوق ائتمانات التنوع البيولوجي في الإمارات في طور النشأة لكنه ينمو بسرعة. يُعدّ برنامج استعادة أشجار المانغروف الواسع في البلاد — الذي يستهدف 100 مليون شجرة بحلول 2030 — مصدراً رئيسياً لكلٍّ من ائتمانات الكربون والتنوع البيولوجي.</p>
<p>بالنسبة للمشترين الدوليين الباحثين عن ائتمانات الكربون والتنوع البيولوجي في الشرق الأوسط، تقدّم الإمارات استقراراً تنظيمياً ودعماً حكومياً قوياً وتوافقاً مع المعايير الدولية.</p>`,
      },
    },
  },
  {
    slug: "abu-dhabi-mangroves-carbon",
    date: "2025-07-15",
    lang: {
      en: {
        title: "Abu Dhabi Mangroves: A Carbon and Biodiversity Powerhouse",
        excerpt: "Abu Dhabi's mangrove ecosystem is one of the Gulf region's most significant carbon sinks and biodiversity hotspots. Here's the science and investment case.",
        content: `<p>Abu Dhabi's mangrove forests, stretching along 300 kilometers of coastline and covering over 160 square kilometers, represent one of the Arabian Peninsula's most significant ecological assets. Dominated by the grey mangrove (Avicennia marina), these coastal forests have expanded significantly under active government restoration programs, now making them the focal point for Gulf blue carbon investment.</p>
<p>The carbon sequestration potential of Abu Dhabi's mangroves is substantial. Studies conducted by New York University Abu Dhabi estimate average belowground carbon stocks of 120-180 tonnes CO2 equivalent per hectare in established mangrove stands — among the highest in the Arabian region. The combination of aboveground biomass and belowground peat accumulation makes mangroves particularly valuable for carbon accounting.</p>
<p>Beyond carbon, Abu Dhabi's mangroves provide critical habitat for endangered species including Socotra cormorants, Western reef herons, and hawksbill sea turtles. This biodiversity value, when certified under standards such as Plan Vivo or the Biodiversity Credit Alliance framework, creates additional revenue streams for mangrove conservation projects.</p>
<p>The Abu Dhabi Environment Agency (EAD) has partnered with international carbon standard bodies to establish a robust certification pathway for UAE mangrove credits. The first verified credit issuances are expected from projects in the Eastern Mangrove Lagoon and Al Jubail Island restoration zones.</p>`,
      },
      ar: {
        title: "أشجار المانغروف في أبوظبي: قوة للكربون والتنوع البيولوجي",
        excerpt: "تُعدّ غابات المانغروف في أبوظبي من أهم المصارف الكربونية ونقاط التنوع البيولوجي في منطقة الخليج. إليك الحجج العلمية والاستثمارية.",
        content: `<p>تمتد غابات المانغروف في أبوظبي على طول 300 كيلومتر من الساحل وتغطي أكثر من 160 كيلومتراً مربعاً، وتمثّل واحدة من أهم الأصول البيئية في شبه الجزيرة العربية. نمت هذه الغابات الساحلية بشكل ملحوظ في إطار برامج الاستعادة الحكومية الفاعلة.</p>
<p>إمكانات احتجاز الكربون في أشجار المانغروف بأبوظبي كبيرة. تُقدّر الدراسات التي أجرتها جامعة نيويورك أبوظبي متوسط مخزون الكربون تحت الأرض بـ 120-180 طناً من مكافئ ثاني أكسيد الكربون لكل هكتار في مناطق المانغروف الراسخة.</p>
<p>علاوة على الكربون، توفر أشجار المانغروف في أبوظبي موئلاً حيوياً للأنواع المهددة بالانقراض، بما فيها الكركر السقطري وطائر الرمال الغربي وسلحفاة الظهر الصفحي.</p>
<p>شراكت هيئة البيئة في أبوظبي (EAD) مع هيئات المعايير الكربونية الدولية لإنشاء مسار اعتماد قوي لائتمانات المانغروف في الإمارات.</p>`,
      },
    },
  },
  {
    slug: "adgm-carbon-markets-uae",
    date: "2025-06-20",
    lang: {
      en: {
        title: "ADGM and Carbon Markets: The UAE's Financial Framework",
        excerpt: "The Abu Dhabi Global Market is building a world-class regulatory infrastructure for carbon credit trading. Here's how it works and why it matters for buyers.",
        content: `<p>The Abu Dhabi Global Market (ADGM) has positioned itself as the Gulf's leading financial center for climate finance and voluntary carbon markets. Following the success of its cryptocurrency and fintech regulatory frameworks, ADGM has applied the same principle — clear rules, international standards alignment, and regulatory sandboxes for innovation — to the emerging carbon credit market.</p>
<p>ADGM's Carbon Exchange (ACX) provides a regulated platform for buying and selling verified carbon credits. Unlike Over-The-Counter (OTC) transactions that dominate most voluntary markets, ACX offers price transparency, standardized contract terms, and counterparty risk protection — addressing key concerns that have historically limited institutional participation in voluntary carbon markets.</p>
<p>The regulatory framework for carbon credits at ADGM is aligned with international standards from Verra, Gold Standard, and the emerging Integrity Council for the Voluntary Carbon Market (ICVCM) Core Carbon Principles. This alignment gives buyers confidence that ADGM-traded credits meet the highest quality thresholds.</p>
<p>For corporate buyers seeking to achieve net-zero commitments with UAE nexus, ADGM offers particular advantages: regulatory certainty, proximity to Gulf-region project supply, and alignment with the UAE's national Net Zero 2050 strategy. Financial institutions including Mubadala, Abu Dhabi National Energy Company (TAQA), and several international banks have already announced carbon credit sourcing programs through ADGM-regulated channels.</p>`,
      },
      ar: {
        title: "مركز أبوظبي للأسواق المالية وأسواق الكربون: الإطار المالي للإمارات",
        excerpt: "يبني مركز أبوظبي للأسواق المالية بنية تحتية تنظيمية عالمية المستوى لتداول ائتمانات الكربون. إليك كيفية عمله وأهميته للمشترين.",
        content: `<p>وضع مركز أبوظبي للأسواق المالية (ADGM) نفسه مركزاً مالياً رائداً في الخليج لتمويل المناخ وأسواق الكربون الطوعية. طبّق ADGM المبدأ ذاته — قواعد واضحة، وتوافق مع المعايير الدولية، وبيئات تنظيمية للابتكار — على سوق ائتمانات الكربون الناشئة.</p>
<p>توفر بورصة الكربون التابعة لـ ADGM (ACX) منصة منظمة لشراء وبيع ائتمانات الكربون الموثّقة. على عكس المعاملات خارج البورصة التي تهيمن على معظم الأسواق الطوعية، تتيح ACX شفافية الأسعار وبنود العقود الموحّدة وحماية مخاطر الأطراف المقابلة.</p>
<p>الإطار التنظيمي لائتمانات الكربون في ADGM متوافق مع المعايير الدولية من Verra وGold Standard ومبادئ الكربون الأساسية من مجلس نزاهة سوق الكربون الطوعي (ICVCM).</p>
<p>بالنسبة للمشترين المؤسسيين الساعين لتحقيق التزامات الحياد الكربوني بصلة بالإمارات، يقدّم ADGM مزايا خاصة: يقيناً تنظيمياً، وقرباً من عرض المشاريع الإقليمية في الخليج، وتوافقاً مع استراتيجية الحياد الكربوني 2050 للإمارات.</p>`,
      },
    },
  },
  {
    slug: "biodiversity-carbon-credits-convergence",
    date: "2026-08-02",
    lang: {
      en: {
        title: "Biodiversity Credits and Carbon Credits: How the UAE Is Bridging the Gap",
        excerpt: "Two nature finance markets that once operated in parallel are converging. The UAE — with ADGM as the regulatory anchor and COP28 as the catalyst — is positioning itself at the intersection.",
        content: `<p>For most of the past decade, the voluntary carbon market and the emerging biodiversity credit market developed along separate tracks. Carbon credits measured tonnes of CO2 avoided or removed; biodiversity credits measured habitat area, species populations, or ecosystem condition indices. Different methodologies, different buyers, different registries. That separation is now dissolving — and the UAE is positioned at the point of convergence.</p>
<p>The structural driver is buyer demand. Corporate sustainability teams increasingly report under TCFD for climate and TNFD for nature — the Taskforce on Nature-related Financial Disclosures, whose framework launched in 2023. The Science Based Targets initiative is developing FLAG standard v2 — covering forest, land, and agriculture companies — in alignment with the Corporate Net-Zero Standard released in June 2026. As these frameworks converge, the incentive to address both carbon and biodiversity through the same project pipeline grows sharper. The GLF Marketplace — the Global Landscapes Forum's credit platform — opened applications for biodiversity conservation and blue carbon projects in 2026, with funding up to $300,000 per project and Asia-Pacific listed alongside Africa as a priority region. These are not incremental signals; they mark the moment biodiversity finance infrastructure is catching up with carbon.</p>
<p>On the regulatory side, Article 6.4 of the Paris Agreement — the international crediting mechanism operationalised through Glasgow and Dubai — explicitly allows "non-greenhouse gas benefits" to be recognised alongside emission reductions. This creates regulatory space for projects to generate carbon credits under Article 6.4 while simultaneously generating biodiversity credits under nature-based frameworks. For project developers, stacking is not just permitted — it is becoming a competitive differentiator that commands a price premium. EU allowances currently trade at approximately €81 per tonne; voluntary credits with certified biodiversity co-benefits consistently price above unadorned carbon offsets from comparable projects.</p>
<p>The UAE offers the clearest example of what convergence looks like in practice. Abu Dhabi's mangrove restoration programmes — targeting 100 million trees by 2030, with the Jubail Mangrove Park as the flagship — generate measurable outcomes on both dimensions. Mangroves sequester 0.6–1.7 tonnes of carbon per hectare per year in aboveground biomass, with substantially more stored belowground in peat. They simultaneously provide habitat for hawksbill sea turtles, Socotra cormorants, and a range of reef fish species. A single certified mangrove project in Abu Dhabi can legitimately issue carbon credits under Verra's VCS methodology and biodiversity credits under Plan Vivo or emerging Biodiversity Credit Alliance frameworks.</p>
<p>ADGM's Nature-Based Solutions regulatory sandbox explicitly supports dual-credit projects. Abu Dhabi's 2030 Nature Conservation Strategy sets quantitative targets for mangrove cover, coral reef restoration, and protected marine area expansion — all translating into project pipelines that credit buyers can support. The Voluntary Carbon Markets Integrity Initiative (VCMI) claims standard now rewards projects with high biodiversity co-benefits with a premium tier, translating nature value directly into price premium.</p>
<p>In July 2026, the UAE published its 'Host Party Participation Requirements for Article 6.4' with the UNFCCC, formally listing eligible project sectors: utility-scale and distributed solar, wind, waste-to-energy, energy efficiency (industrial, buildings, district cooling, transport), mangrove restoration, afforestation, ecosystem restoration, and blue carbon. Crucially, the UAE is positioning itself as both a buyer AND a seller under Article 6.4 — it has already signed a Memorandum of Understanding with Paraguay at COP28, and joined Japan's Joint Crediting Mechanism in April 2024.</p>
<p>For buyers, the convergence delivers three practical advantages. First, a smaller number of higher-quality projects can simultaneously address both climate and nature reporting obligations. Second, UAE projects — with their dual certification pathways and ADGM regulatory infrastructure — offer a functioning model of what stacked credits look like in a regulated market. Third, as TNFD reporting becomes mandatory in several jurisdictions and investors increasingly scrutinise nature-related risks, early-mover advantage in biodiversity credit procurement will matter more than it does today.</p>
<p>The walls between carbon and biodiversity markets are coming down. In the UAE, with its mangrove coastlines, evolving regulatory architecture, and COP28 diplomatic capital, they were never particularly high. Read more about ADGM's carbon market framework and Abu Dhabi's mangrove restoration programmes in our other articles on this site.</p>`,
      },
      ar: {
        title: "اعتمادات التنوع البيولوجي واعتمادات الكربون: كيف تجمع الإمارات بينهما",
        excerpt: "سوقان لتمويل الطبيعة كانا يعملان بشكل منفصل بدآ في التقارب. الإمارات، بمركز أبوظبي للأسواق المالية محركاً تنظيمياً ومؤتمر COP28 حافزاً، تضع نفسها عند نقطة التقاطع.",
        content: `<p>طوال معظم العقد الماضي، تطوّر سوق الكربون الطوعي وسوق ائتمانات التنوع البيولوجي الناشئ على مسارين منفصلين. كانت ائتمانات الكربون تقيس أطنان ثاني أكسيد الكربون المُتجنَّبة أو المُزالة؛ وكانت ائتمانات التنوع البيولوجي تقيس مساحة الموئل أو أعداد الأنواع أو مؤشرات حالة النظام البيئي. منهجيات مختلفة، ومشترون مختلفون، وسجلات مختلفة. هذا الفصل يتلاشى الآن — والإمارات تتموضع عند نقطة التقارب.</p>
<p>المحرّك الهيكلي هو طلب المشترين. تُعدّ فرق الاستدامة في الشركات تقاريرها الآن وفق إطار TCFD للمناخ وإطار TNFD للطبيعة. تُطوّر مبادرة الأهداف المبنية على العلم نسخة FLAG v2 الخاصة بشركات الغابات والأراضي والزراعة، بما يتوافق مع المعيار المؤسسي لصافي الصفر الصادر في يونيو 2026. وقد فتح GLF Marketplace — منصة ائتمانات المنتدى العالمي للمناظر الطبيعية — طلبات للحصول على تمويل لمشاريع التنوع البيولوجي والكربون الأزرق في 2026، بتمويل يصل إلى 300,000 دولار لكل مشروع مع منح منطقة آسيا والمحيط الهادئ أولوية. هذه إشارات نضج حقيقي لبنية تمويل التنوع البيولوجي.</p>
<p>على الصعيد التنظيمي، تسمح المادة 6.4 من اتفاقية باريس صراحةً بالاعتراف بـ"فوائد غير ناجمة عن غازات الدفيئة" إلى جانب تخفيضات الانبعاثات، ما يتيح لمطوري المشاريع توليد ائتمانات الكربون وائتمانات التنوع البيولوجي في آنٍ واحد. تتداول حصص الاتحاد الأوروبي حالياً بنحو €81 للطن؛ وتُسعَّر ائتمانات الكربون الطوعية المصحوبة بمزايا مصادقة على التنوع البيولوجي باستمرار فوق نظيراتها غير المعززة من مشاريع مماثلة.</p>
<p>تُقدّم الإمارات المثال الأوضح على ما يبدو عليه التقارب عملياً. برامج استعادة أشجار المانغروف في أبوظبي — التي تستهدف 100 مليون شجرة بحلول 2030، مع حديقة مانغروف الجبيل نموذجاً — تُنتج نتائج قابلة للقياس على البُعدين معاً. تحتجز أشجار المانغروف 0.6–1.7 طن من الكربون لكل هكتار سنوياً، وتوفر في الوقت ذاته موئلاً لسلحفاة الظهر الصفحي والكركر السقطري وعدد من أنواع الأسماك الشعابية. يمكن لمشروع مانغروف واحد معتمد في أبوظبي إصدار ائتمانات كربون وائتمانات تنوع بيولوجي بموجب معايير دولية معترف بها.</p>
<p>تدعم بيئة ADGM التنظيمية التجريبية للحلول القائمة على الطبيعة مشاريع الائتمان المزدوج صراحةً. تضع استراتيجية أبوظبي 2030 لصون الطبيعة أهدافاً كمية لغطاء المانغروف واستعادة الشعاب المرجانية وتوسيع المناطق البحرية المحمية. يكافئ معيار مطالبات مبادرة VCMI الآن المشاريع ذات المزايا المصاحبة العالية للتنوع البيولوجي بفئة مميزة تُترجم قيمة الطبيعة إلى علاوة سعرية مباشرة.</p>
<p>في يوليو 2026، نشرت الإمارات "متطلبات مشاركة الطرف المضيف للمادة 6.4" مع الأمم المتحدة لتغير المناخ (UNFCCC)، مع إدراج رسمي لقطاعات المشاريع المؤهلة: الطاقة الشمسية على نطاق واسع والموزعة، وطاقة الرياح، والطاقة من النفايات، وكفاءة الطاقة (الصناعة، والمباني، والتبريد المركزي، والنقل)، واستعادة أشجار المانغروف، والتحريج، واستعادة النظم البيئية، والكربون الأزرق. والأهم من ذلك، أن الإمارات تضع نفسها مشترياً وبائعاً في آنٍ واحد في إطار المادة 6.4 — فقد وقّعت بالفعل مذكرة تفاهم مع باراغواي في COP28، وانضمت إلى آلية الائتمان المشترك اليابانية في أبريل 2024.</p>
<p>بالنسبة للمشترين، يُقدّم التقارب ثلاث مزايا عملية: معالجة التزامات الإبلاغ المناخية والطبيعية في آنٍ واحد، ومشاريع الإمارات كنموذج عملي للائتمانات المتراكمة في سوق منظَّم، وميزة الريادة في ظل تنامي متطلبات الإفصاح المتعلق بالطبيعة. اقرأ المزيد عن إطار سوق الكربون في ADGM ومشاريع استعادة أشجار المانغروف في أبوظبي في المقالات الأخرى على هذا الموقع.</p>`,
      },
    },
  },
  {
    slug: "central-asia-gulf-carbon-hubs",
    date: "2026-08-02",
    lang: {
      en: {
        title: "The UAE and Kazakhstan: Unlikely Partners in Building Regional Carbon Markets",
        excerpt: "Two countries with outsized fossil fuel histories are racing to lead their regions' clean finance transitions. The UAE's Gulf position and Kazakhstan's Central Asian reach make them natural counterparts.",
        content: `<p>Two countries with outsized fossil fuel histories are leading their respective regions' transitions into climate finance. The United Arab Emirates, anchored by ADGM's regulatory infrastructure and the diplomatic heft of COP28, and Kazakhstan, powered by a decade of mandatory emissions trading and the institutional ambition of the AIFC, are both racing to become the dominant carbon trading centre for their regions. Together, they represent something increasingly significant: a Caspian-to-Gulf carbon corridor in the making.</p>
<p>The UAE's strengths begin with financial architecture. The Abu Dhabi Global Market (ADGM) built the Gulf's first regulated voluntary carbon exchange — the Abu Dhabi Carbon Exchange (ACX) — with institutional-grade custody, price transparency, and a Nature-Based Solutions regulatory sandbox explicitly supporting dual carbon-and-biodiversity credit projects. COP28 in Dubai produced the UAE Consensus on tripling renewable energy capacity and phasing down fossil fuels, placing the UAE at the diplomatic centre of global climate finance. An Abu Dhabi Carbon Credit Exchange is now in development, targeting project supply from the Gulf, Red Sea, East Africa, and Indian Ocean basin. The UAE is not the only Gulf sovereign moving: in July 2026, Saudi Arabia registered its first project under GCOM — the Gulf's Greenhouse Gases Crediting and Offsetting Mechanism — with first voluntary credit sales planned for November 2026 and a mandatory ETS targeted for 2027. The UAE sits within a Gulf that is collectively building carbon market depth.</p>
<p>The UAE formalised its Article 6.4 ambitions in July 2026 by publishing its Host Party Participation Requirements at UNFCCC, explicitly listing mangrove restoration, blue carbon, and renewable energy as eligible project types — confirming that Abu Dhabi's natural capital is on the table as an international credit-generating asset. The EU ETS aviation extension proposal (July 2026) — which would impose additional costs of €28-85 per return ticket on routes to the Middle East — directly threatens airlines like Emirates; the carbon cost pressure may accelerate demand for Corsia-compliant offsets from the region.</p>
<p>The Gulf's carbon demand story is also being shaped by aviation policy. The EU has proposed extending its ETS to all flights within 5,000 kilometres of Frankfurt — a perimeter that covers routes to North Africa and the Middle East. With EU allowances trading at approximately €81 per tonne versus CORSIA eligible emissions units at a fraction of that cost, the pressure on Gulf-connected aviation to source carbon credits is intensifying. For UAE-based project developers, this represents a significant new buyer channel alongside the voluntary corporate market.</p>
<p>Kazakhstan brings different but complementary strengths to the broader corridor. The KAZ ETS, running since 2013, is one of Asia's oldest mandatory cap-and-trade systems, covering approximately 150 large emitters across energy, mining, and manufacturing. The Astana International Financial Centre (AIFC) — operating under English common law — is developing voluntary credit standards for Central Asian project types: steppe grassland restoration, peatland rewetting, and methane capture from coal mines. In July 2026, GIZ launched a tender for a biochar feasibility study in Tajikistan — the first step of European development finance into Central Asia's carbon space — with Kazakhstan's AIFC positioned as the natural institutional destination for the credits such projects will generate. Kazakhstan's net-zero target is 2060, backed by NDC commitments to reduce emissions 15–25% below 1990 levels by 2030.</p>
<p>What the two countries share is equally significant. Both deploy sovereign wealth capital as a market-building tool — the UAE through Mubadala and ADQ, Kazakhstan through its National Fund and Samruk-Kazyna. Both sit at the intersection of major trading blocs: the UAE bridges South Asia, East Africa, and Europe; Kazakhstan borders China and Russia and plans to link its ETS with both. Both have made carbon market infrastructure a national strategic priority rather than a side project of their economic diversification agendas.</p>
<p>The structural differences matter for buyers. The UAE leads with voluntary market depth and financial services infrastructure; Kazakhstan leads with compliance-driven demand and land-mass project supply. Together, they represent opposite ends of a potential Silk Road carbon corridor — UAE financial architecture combined with Central Asian project pipelines — that AIFC and ADGM representatives have both referenced publicly. For corporate buyers seeking Gulf-regional credits with strong provenance and regulatory backing, the UAE remains the natural entry point. But the cross-market story is where the longer-term opportunity lies. Read the full Kazakhstan carbon market guide at CarbonCredits.kz for more on the eastern end of this corridor.</p>`,
      },
      ar: {
        title: "الإمارات وكازاخستان: شركاء غير متوقعين في بناء أسواق الكربون الإقليمية",
        excerpt: "دولتان ذواتا تاريخ حافل في الوقود الأحفوري تتسابقان لقيادة التحولات المالية النظيفة في منطقتيهما. يجعلهما موقع الإمارات في الخليج وامتداد كازاخستان في آسيا الوسطى نظيرَين طبيعيَّين.",
        content: `<p>دولتان ذواتا تاريخ حافل في مجال الوقود الأحفوري تقودان انتقال منطقتيهما نحو تمويل المناخ. الإمارات العربية المتحدة، بدعم من البنية التحتية التنظيمية لـ ADGM والثقل الدبلوماسي لـ COP28، وكازاخستان، المدعومة بنظام تداول انبعاثات إلزامي يعمل منذ عقد والطموح المؤسسي لـ AIFC، تتسابقان لتصبح مركز التداول الكربوني المهيمن في منطقتيهما. معاً، يمثّلان ممرّاً كربونياً ناشئاً يمتد من الكاسبي إلى الخليج.</p>
<p>تتجذّر نقاط قوة الإمارات في البنية المالية. بنى ADGM أول بورصة كربون طوعية منظَّمة في الخليج — Abu Dhabi Carbon Exchange (ACX) — مع حضانة مؤسسية وشفافية في الأسعار وبيئة تنظيمية تجريبية تدعم مشاريع الائتمان المزدوج. أسفر COP28 في دبي عن توافق الإمارات على مضاعفة الطاقة المتجددة ثلاث مرات. الإمارات ليست الوحيدة: في يوليو 2026، سجّلت المملكة العربية السعودية أول مشروع لها في إطار GCOM — آلية ائتمان انبعاثات الغازات الدفيئة في الخليج — مع تخطيط لأول مبيعات ائتمانية طوعية في نوفمبر 2026 ونظام ETS إلزامي في 2027. الخليج يبني عمقاً جماعياً في سوق الكربون.</p>
<p>رسّخت الإمارات طموحاتها في إطار المادة 6.4 في يوليو 2026 بنشر متطلبات مشاركة الطرف المضيف على المستوى الأممي لتغير المناخ (UNFCCC)، مع إدراج صريح لاستعادة أشجار المانغروف والكربون الأزرق والطاقة المتجددة ضمن أنواع المشاريع المؤهلة — ما يؤكد أن رأس المال الطبيعي في أبوظبي معروض كأصل توليد ائتمانات دولية. واقتراح توسيع نطاق الاتحاد الأوروبي لنظام ETS (يوليو 2026) — الذي قد يفرض تكاليف إضافية تتراوح بين €28 و€85 لكل تذكرة ذهاب وإياب على الطرق المتجهة إلى الشرق الأوسط — يهدد مباشرةً شركات الطيران كالإمارات؛ وقد يُعجِّل الضغط الكربوني الطلبَ على أرصدة كربونية متوافقة مع كورسيا من المنطقة.</p>
<p>اقترح الاتحاد الأوروبي توسيع نطاق ETS ليشمل الرحلات في نطاق 5,000 كيلومتر من فرانكفورت — ما يغطي طرقاً إلى الشرق الأوسط. بأسعار EUA تبلغ نحو €81 للطن، يتصاعد الضغط على شركات الطيران المرتبطة بالخليج لاقتناء ائتمانات كربون، ما يُوجِد قناة طلب جديدة مهمة لمطوّري المشاريع الإماراتيين.</p>
<p>تُقدّم كازاخستان نقاط قوة مختلفة لكنها تكميلية. تُعدّ KAZ ETS التي تعمل منذ 2013 واحدة من أقدم أنظمة التداول الإلزامية في آسيا، تغطي نحو 150 مُصدِّراً صناعياً كبيراً. يعمل AIFC وفق القانون الإنجليزي العام ويُطوّر معايير ائتمانية للمشاريع في آسيا الوسطى. في يوليو 2026، أطلقت GIZ مناقصة لدراسة جدوى الفحم الحيوي في طاجيكستان — الخطوة الأولى للتمويل الأوروبي الإنمائي في مساحة الكربون بآسيا الوسطى — مع كازاخستان وAIFC كوجهة مؤسسية طبيعية للائتمانات التي ستُولِّدها هذه المشاريع.</p>
<p>ما يجمع البلدين لا يقل أهمية. كلاهما يوظّف رأس المال السيادي أداةً لبناء السوق. كلاهما أولى بناء البنية التحتية لسوق الكربون أولوية استراتيجية وطنية. الاختلافات الهيكلية مهمة للمشترين: الإمارات تقود بعمق السوق الطوعي والخدمات المالية؛ كازاخستان تقود بالطلب المدفوع بالامتثال ومساحة المشاريع. معاً يمثّلان طرفَي ممرّ كربوني محتمل على طريق الحرير يجمع البنية المالية الإماراتية مع خطوط أنابيب المشاريع من آسيا الوسطى. بالنسبة للمشترين المؤسسيين الباحثين عن ائتمانات الخليج، تظل الإمارات نقطة الدخول الطبيعية. اقرأ الدليل الكامل لسوق الكربون في كازاخستان على CarbonCredits.kz لمعرفة المزيد عن الطرف الشرقي من هذا الممر.</p>`,
      },
    },
  },
];

export function getPost(slug: string): Post | undefined {
  return posts.find(p => p.slug === slug);
}
